# Generated by Django 2.2.5 on 2020-05-23 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_code', models.CharField(default='1DF56HJ9JK8L6T', max_length=20)),
                ('treated', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='are', to='Locations.Area')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit', to='Locations.City')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa', to='Base.PaymentType')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinc', to='Locations.Province')),
            ],
        ),
    ]
