# Generated by Django 2.2.5 on 2020-04-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area1', models.CharField(default='test', max_length=20)),
                ('birth_year', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_code', models.CharField(default='1DF56HJ9JK8L6T', max_length=20)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
