# Generated by Django 2.2.5 on 2020-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompleteIdentity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeidentity',
            name='area1',
        ),
        migrations.AddField(
            model_name='completeidentity',
            name='area',
            field=models.CharField(default='ar', max_length=20),
        ),
    ]
