# Generated by Django 2.2.5 on 2020-04-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompleteIdentity', '0002_auto_20200420_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeidentity',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar', to='Locations.Area'),
        ),
    ]
