# Generated by Django 2.2.5 on 2020-05-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0002_auto_20200501_1530'),
        ('CompleteIdentity', '0003_auto_20200420_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeidentity',
            name='area',
        ),
        migrations.AddField(
            model_name='completeidentity',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ar', to='Locations.Province'),
            preserve_default=False,
        ),
    ]
