# Generated by Django 2.2.5 on 2020-05-23 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminiUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_city_admin', models.BooleanField(default=False)),
                ('is_area_admin', models.BooleanField(default=False)),
                ('is_district_admin', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.City')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.District')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
