# Generated by Django 2.2.5 on 2020-05-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='district',
        ),
        migrations.RemoveField(
            model_name='city',
            name='area',
        ),
        migrations.AddField(
            model_name='province',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Locations.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Locations.District'),
            preserve_default=False,
        ),
    ]
