# Generated by Django 2.2.5 on 2020-04-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=1)),
                ('no_identity', models.CharField(max_length=20)),
                ('given_place', models.CharField(max_length=20)),
                ('road', models.CharField(default='Vide', max_length=50)),
                ('birth_date', models.CharField(max_length=20)),
                ('father_fullname', models.CharField(max_length=20)),
                ('mother_fullname', models.CharField(max_length=20)),
                ('profession', models.CharField(default='Sans', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('matri_no', models.CharField(max_length=20)),
                ('civil_state', models.CharField(default='Célibataire', max_length=100)),
                ('nationality', models.CharField(default='Burundaise', max_length=100)),
                ('birth_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ba', to='Locations.Area')),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bc', to='Locations.City')),
                ('birth_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bd', to='Locations.District')),
                ('birth_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp', to='Locations.Province')),
                ('residence_area', models.ForeignKey(default='Ok', on_delete=django.db.models.deletion.CASCADE, related_name='a', to='Locations.Area')),
                ('residence_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cit', to='Locations.City')),
                ('residence_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis', to='Locations.District')),
                ('residence_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='Locations.Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'no_identity', 'birth_province')},
            },
        ),
    ]
