# Generated by Django 2.2.5 on 2020-05-23 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='M', max_length=1)),
                ('no_identity', models.CharField(default='Vide', max_length=100)),
                ('given_place', models.CharField(default='Vide', max_length=100)),
                ('given_date', models.CharField(default='00/00/0000', max_length=10)),
                ('birth_date', models.CharField(default='Vide', max_length=100)),
                ('father_fullname', models.CharField(default='Vide', max_length=100)),
                ('mother_fullname', models.CharField(default='Vide', max_length=100)),
                ('profession', models.CharField(default='Sans', max_length=100)),
                ('phone_number', models.CharField(default='Vide', max_length=100)),
                ('matri_no', models.CharField(default='Vide', max_length=100)),
                ('civil_state', models.CharField(default='Célibataire', max_length=100)),
                ('nationality', models.CharField(default='Burundaise', max_length=100)),
                ('staff_member', models.BooleanField(default=0)),
                ('birth_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ba', to='Locations.Area')),
                ('birth_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bc', to='Locations.City')),
                ('birth_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bd', to='Locations.District')),
                ('birth_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp', to='Locations.Province')),
                ('residence_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra', to='Locations.Area')),
                ('residence_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rc', to='Locations.City')),
                ('residence_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rd', to='Locations.District')),
                ('residence_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp', to='Locations.Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'no_identity', 'birth_date', 'nationality')},
            },
        ),
    ]
