# Generated by Django 2.2.5 on 2020-04-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='road',
        ),
    ]
