# Generated by Django 2.2.5 on 2020-05-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cni_one',
            field=models.ImageField(blank=True, null=True, upload_to='CNI/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='cni_two',
            field=models.ImageField(blank=True, null=True, upload_to='CNI/'),
        ),
    ]
