# Generated by Django 2.2.5 on 2020-05-01 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cni', '0003_auto_20200501_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='simple_user',
            field=models.CharField(default='Simple', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='profil',
            unique_together={('user', 'no_identity', 'birth_date', 'simple_user')},
        ),
    ]
